import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { z } from 'zod'
import { TOOL_METADATA } from '../src/tools/tool-metadata.js'

interface ArgInfo {
  name: string
  type: string
  required: boolean
  defaultValue: string
  description: string
}

function resolveZodType(schema: z.ZodType): {
  type: string
  required: boolean
  defaultValue: string
  description: string
} {
  let required = true
  let defaultValue = '-'
  const description = schema.description ?? '-'

  // Unwrap default → optional → inner type
  let current: z.ZodType = schema

  if (current instanceof z.ZodDefault) {
    const def = (current as z.ZodDefault<z.ZodType>)._def
    defaultValue = JSON.stringify(def.defaultValue)
    required = false
    current = def.innerType as z.ZodType
  }

  if (current instanceof z.ZodOptional) {
    required = false
    current = (current as z.ZodOptional<z.ZodType>)._def.innerType as z.ZodType
  }

  const type = getTypeName(current)

  return { type, required, defaultValue, description }
}

function getTypeName(schema: z.ZodType): string {
  if (schema instanceof z.ZodString) return 'string'
  if (schema instanceof z.ZodNumber) return 'number'
  if (schema instanceof z.ZodBoolean) return 'boolean'
  if (schema instanceof z.ZodArray) {
    const element = (schema as z.ZodArray<z.ZodType>)._def.element as z.ZodType
    return `${getTypeName(element)}[]`
  }
  if (schema instanceof z.ZodEnum) {
    const entries = (schema as z.ZodEnum<[string, ...string[]]>)._def.entries as Record<
      string,
      string
    >
    return Object.values(entries)
      .map((v) => `"${v}"`)
      .join(' \\| ')
  }
  return 'unknown'
}

function schemaToArgs(schema: z.ZodRawShape): ArgInfo[] {
  return Object.entries(schema).map(([name, zodType]) => {
    const { type, required, defaultValue, description } = resolveZodType(zodType as z.ZodType)
    return { name, type, required, defaultValue, description }
  })
}

function generateArgTable(args: ArgInfo[]): string {
  const lines = [
    '| 引数 | 型 | 必須 | デフォルト | 説明 |',
    '|------|------|------|------------|------|',
  ]
  for (const arg of args) {
    lines.push(
      `| ${arg.name} | ${arg.type} | ${arg.required ? 'Yes' : 'No'} | ${arg.defaultValue} | ${arg.description} |`,
    )
  }
  return lines.join('\n')
}

export function generateMarkdown(): string {
  const lines: string[] = [
    '<!-- このファイルは自動生成です。手動で編集しないでください。 -->',
    '<!-- Generated by: pnpm --filter @claude-memory/mcp-server docs:generate -->',
    '',
    '# MCP ツールリファレンス',
    '',
  ]

  for (const tool of TOOL_METADATA) {
    lines.push(`### ${tool.name}`)
    lines.push('')
    lines.push(tool.description)
    lines.push('')

    if (tool.schema === null) {
      lines.push('引数なし')
    } else {
      const args = schemaToArgs(tool.schema)
      lines.push(generateArgTable(args))
    }

    lines.push('')
  }

  return lines.join('\n')
}

// CLI entry point
const isMainModule = process.argv[1]?.includes('generate-docs')
if (isMainModule) {
  const markdown = generateMarkdown()
  const outPath = resolve(import.meta.dirname ?? '.', '../../../docs/generated/mcp-tools.md')
  writeFileSync(outPath, markdown, 'utf-8')
  console.log(`Generated: ${outPath}`)
}
